name: example
description: Simple Architecture for Flutter Example App
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dart_mappable: ^3.3.1
  flutter:
    sdk: flutter
  simple_architecture:
    path: ..

dev_dependencies:
  build_runner: ^2.4.6
  dart_mappable_builder: ^3.3.0
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
