name: simple_architecture
description: Simple Architecture for Flutter apps with Dependency Injection, Mediator Pattern and Observable Streams
version: 0.2310.0601
homepage: https://github.com/kodel-dynamics/simple_architecture

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
