name: simple_architecture
description: Simple Architecture for Flutter apps with Dependency Injection,
  Mediator Pattern and Observable Streams
version: 1.231020.3
homepage: https://pub.dev/packages/simple_architecture
repository: https://github.com/kodel-dynamics/simple_architecture

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
